Repository tlsfuzzer/tlsfuzzer, pull requests merged in 2018-07, with the labels that each got.

#419 deduplicate code in empty-alert add test for handshake keys
  scripts/test-tls13-empty-alert.py
Labels: enhancement

#425 restore CI support for python 3.2
  .travis.yml
  build-requirements-2.6.txt
  build-requirements-3.2.txt
  build-requirements.txt
Labels: maintenance

#416 test-script for specific number of SessionTickets
  scripts/test-tls13-count-tickets.py
  tests/tlslite-ng-random-subset.json
  tests/tlslite-ng.json
Labels: new test script

#427 Session resumption
  scripts/test-tls13-session-resumption.py
  tests/test_tlsfuzzer_expect.py
  tests/test_tlsfuzzer_helpers.py
  tests/test_tlsfuzzer_messages.py
  tests/tlslite-ng-random-subset.json
  tests/tlslite-ng.json
  tlsfuzzer/expect.py
  tlsfuzzer/helpers.py
  tlsfuzzer/messages.py
Labels: enhancement, new test script

#438 test-large-hello - don't send TLS 1.3 extensions in the test
  scripts/test-large-hello.py
Labels: bug

#432 signature_algorithms_cert compatibility
  scripts/test-certificate-malformed.py
  scripts/test-certificate-request.py
  scripts/test-certificate-verify-malformed-sig.py
  scripts/test-certificate-verify-malformed.py
  scripts/test-certificate-verify.py
  scripts/test-clienthello-md5.py
  scripts/test-dhe-rsa-key-exchange-signatures.py
  scripts/test-ecdsa-sig-flexibility.py
  scripts/test-extended-master-secret-extension-with-client-cert.py
  scripts/test-invalid-server-name-extension-resumption.py
  scripts/test-invalid-server-name-extension.py
  scripts/test-rsa-pss-sigs-on-certificate-verify.py
  scripts/test-rsa-sigs-on-certificate-verify.py
  scripts/test-sig-algs.py
  scripts/test-signature-algorithms.py
  scripts/test-tls13-0rtt-garbage.py
  scripts/test-tls13-conversation.py
  scripts/test-tls13-count-tickets.py
  scripts/test-tls13-empty-alert.py
  scripts/test-tls13-finished.py
  scripts/test-tls13-hrr.py
  scripts/test-tls13-legacy-version.py
  scripts/test-tls13-nociphers.py
  scripts/test-tls13-pkcs-signature.py
  scripts/test-tls13-record-padding.py
  scripts/test-tls13-rsa-signatures.py
  scripts/test-tls13-rsapss-signatures.py
  scripts/test-tls13-session-resumption.py
  scripts/test-tls13-signature-algorithms.py
  scripts/test-tls13-version-negotiation.py
  scripts/test-tls13-zero-length-data.py
  scripts/test-x25519.py
  tests/verify-scripts-json.py
  tlsfuzzer/helpers.py
Labels: maintenance

#437 Robust(er) finished script
  scripts/test-tls13-finished.py
  tests/test_tlsfuzzer_expect.py
  tlsfuzzer/expect.py
Labels: bug

#436 FFDHE test script
  scripts/test-tls13-ffdhe-sanity.py
  tests/tlslite-ng-random-subset.json
  tests/tlslite-ng.json
  tlsfuzzer/helpers.py
Labels: new test script
