Repository tlsfuzzer/tlsfuzzer, pull requests merged in 2018-06, with the labels that each got.

#400 remove unnecessary assignments in sslv2 scripts
  scripts/test-sslv2-connection.py
  scripts/test-sslv2-force-cipher-3des.py
  scripts/test-sslv2-force-cipher-non3des.py
  scripts/test-sslv2-force-cipher.py
  scripts/test-sslv2-force-export-cipher.py
  scripts/test-sslv2hello-protocol.py
Labels: maintenance

#401 add codeclimate coverage metrics
  .travis.yml
Labels: maintenance

#403 extend tests for SSLv3 padding, add negative test
  requirements.txt
  scripts/test-SSLv3-padding.py
  tests/tlslite-ng-random-subset.json
  tests/tlslite-ng.json
Labels: new test script

#396 HelloRetryRequest support
  README.md
  scripts/test-tls13-hrr.py
  tests/test_tlsfuzzer_expect.py
  tests/test_tlsfuzzer_messages.py
  tests/tlslite-ng-random-subset.json
  tests/tlslite-ng.json
  tlsfuzzer/expect.py
  tlsfuzzer/messages.py
Labels: enhancement, new test script

#404 Implement psk_ke
  requirements.txt
  scripts/test-tls13-psk_ke.py
  tests/test_tlsfuzzer_expect.py
  tests/test_tlsfuzzer_helpers.py
  tests/test_tlsfuzzer_messages.py
  tests/tlslite-ng-random-subset.json
  tests/tlslite-ng.json
  tlsfuzzer/expect.py
  tlsfuzzer/helpers.py
  tlsfuzzer/messages.py
Labels: enhancement

#408 Missing test
  tests/tlslite-ng-random-subset.json
Labels: maintenance

#407 expect server to transition to ap keys after server Finished
  README.md
  requirements.txt
  scripts/test-tls13-zero-length-data.py
  tests/test_tlsfuzzer_expect.py
  tests/test_tlsfuzzer_messages.py
  tlsfuzzer/expect.py
  tlsfuzzer/messages.py
Labels: bug

#409 add psk_dhe_ke test script
  scripts/test-tls13-psk_dhe_ke.py
  tests/tlslite-ng-random-subset.json
  tests/tlslite-ng.json
Labels: new test script

#410 test-script for tls1.3 rsa signatures
  scripts/test-tls13-rsa-signatures.py
  scripts/test-tls13-rsapss-signatures.py
  tests/serverRSAPSSCert.pem
  tests/serverRSAPSSKey.pem
  tests/tlslite-ng-random-subset.json
  tests/tlslite-ng.json
Labels: new test script

#415 Missing tests
  scripts/test-ssl-death-alert.py
  tests/test_tlsfuzzer_helpers.py
  tests/tlslite-ng-random-subset.json
  tests/tlslite-ng.json
  tlsfuzzer/helpers.py
Labels: enhancement, maintenance

#411 Issue 212 tls13 finished fuzzing
  scripts/test-tls13-finished.py
  tests/test_tlsfuzzer_messages.py
  tests/tlslite-ng-random-subset.json
  tests/tlslite-ng.json
  tlsfuzzer/messages.py
  tlsfuzzer/runner.py
Labels: new test script

#414 Added the script for issue #156
  .travis.yml
  Makefile
  tests/verify-scripts-json.py
Labels: maintenance
