Repository tlsfuzzer/tlsfuzzer, pull requests merged in 2018-08, with the labels that each got.

#435 update the test-fuzzed-padding.py
  scripts/test-fuzzed-padding.py
Labels: bug, maintenance

#440 add test-script for unrecognized groups
  scripts/test-tls13-unrecognised-groups.py
  tests/tlslite-ng-random-subset.json
  tests/tlslite-ng.json
Labels: new test script

#443 Quick init for test scripts
  scripts/test-tls13-finished.py
  tests/test_tlsfuzzer_helpers.py
  tests/tlslite-ng-random-subset.json
  tlsfuzzer/helpers.py
Labels: enhancement

#446 scripts: tolerate NST before sending client Finished
  scripts/test-tls13-zero-length-data.py
Labels: bug

#444 make the test-tls13-finished.py more robust, report better errors when it fails
  scripts/test-tls13-finished.py
  tests/test_tlsfuzzer_runner.py
  tlsfuzzer/runner.py
Labels: bug
