Repository tlsfuzzer/tlsfuzzer, pull requests merged in 2018-12, with the labels that each got.

#478 change requirements for python 2.6 (idna package)
  build-requirements-2.6.txt
Labels: maintenance

#479 Add test to verify downgrade protection
  requirements.txt
  scripts/test-downgrade-protection.py
  tests/test_tlsfuzzer_expect.py
  tests/tlslite-ng-random-subset.json
  tests/tlslite-ng.json
  tlsfuzzer/expect.py
Labels: enhancement, new test script

#481 update the package dependencies for Fedora 29
  CONTRIBUTING.md
Labels: maintenance

#485 No sslv2hello test
  scripts/test-sslv2hello-protocol.py
Labels: enhancement

#489 invalid-compression-methods - be strict with expected alerts
  scripts/test-invalid-compression-methods.py
Labels: new test script
