Repository tlsfuzzer/tlsfuzzer, pull requests merged in 2018-05, with the labels that each got.

#294 Update issue templates to new style
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Feature_request.md
  .github/ISSUE_TEMPLATE/New_test_script.md
Labels: maintenance

#233 remove duplicated TestConnect class
  tests/test_tlsfuzzer_messages.py
Labels: bug

#300 contributing guidelines
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  README.md
Labels: maintenance

#386 Add new command node class AddRecordPadding
  scripts/test-tls13-record-padding.py
  tests/test_tlsfuzzer_messages.py
  tests/tlslite-ng-random-subset.json
  tests/tlslite-ng.json
  tlsfuzzer/messages.py
Labels: enhancement, new test script

#380 test TLS 1.3 version negotiation
  scripts/test-tls13-version-negotiation.py
  tests/tlslite-ng-random-subset.json
  tests/tlslite-ng.json
Labels: new test script

#384 TLS 1.3 zero-length data messages test
  README.md
  requirements.txt
  scripts/test-tls13-zero-length-data.py
  tests/tlslite-ng-random-subset.json
  tests/tlslite-ng.json
Labels: new test script

#382 new test-script for ssl3 legacy-version check
  scripts/test-tls13-legacy-version.py
  tests/tlslite-ng-random-subset.json
  tests/tlslite-ng.json
Labels: new test script

#181 Test on Python 3.6 too
  .travis.yml
  requirements.txt
Labels: enhancement, maintenance

#391 TLS1.3: random session_id for ClientHello
  tests/test_tlsfuzzer_messages.py
  tlsfuzzer/messages.py
Labels: enhancement, review request
