Repository tlsfuzzer/tlsfuzzer, pull requests merged in 2019-01, with the labels that each got.

#490 rsa-pss-sigs-on-certificate-verify - be strict with receiving alerts
  scripts/test-rsa-pss-sigs-on-certificate-verify.py
Labels: bug

#492 add tests around legacy renegotiation
  scripts/test-legacy-renegotiation.py
  scripts/test-renegotiation-disabled.py
  tests/tlslite-ng-random-subset.json
  tests/tlslite-ng.json
Labels: new test script

#491 Add test to check tls13 client certificates
  README.md
  requirements.txt
  scripts/test-tls13-certificate-request.py
  tests/test_tlsfuzzer_messages.py
  tests/tlslite-ng-random-subset.json
  tests/tlslite-ng.json
  tlsfuzzer/messages.py
Labels: enhancement, new test script

#493 Fixes to Signature Algorithms
  README.md
  requirements.txt
  scripts/test-rsa-pss-sigs-on-certificate-verify.py
  tests/test_tlsfuzzer_expect.py
  tests/test_tlsfuzzer_messages.py
  tests/tlslite-ng-random-subset.json
  tests/tlslite-ng.json
  tlsfuzzer/expect.py
  tlsfuzzer/messages.py
Labels: bug

#495 Do not allow pkcs1 sig algs with TLS 1.3 protocol
  tests/test_tlsfuzzer_messages.py
  tlsfuzzer/messages.py
Labels: bug

#494 Record size limit extension
  .travis.yml
  Makefile
  README.md
  requirements.txt
  scripts/test-record-size-limit.py
  tests/scripts_retention.py
  tests/test_file.txt
  tests/test_tlsfuzzer_expect.py
  tests/tlslite-ng-random-subset.json
  tests/tlslite-ng.json
  tlsfuzzer/expect.py
  tlsfuzzer/messages.py
  tlsfuzzer/runner.py
Labels: enhancement, new test script

#497 add CI with Python 3.7
  .travis.yml
Labels: maintenance

#498 fix tests to accept the default of 2 tickets from tlslite-ng
  README.md
  requirements.txt
  scripts/test-tls13-pkcs-signature.py
  tests/tlslite-ng-random-subset.json
  tests/tlslite-ng.json
Labels: maintenance

#496 Add test to check TLS1.3 refuses invalid/unsupported signatures
  USAGE.md
  scripts/test-tls13-certificate-verify.py
  tests/test_tlsfuzzer_messages.py
  tests/tlslite-ng-random-subset.json
  tests/tlslite-ng.json
  tlsfuzzer/messages.py
Labels: complex, new test script
