Repository tlsfuzzer/tlsfuzzer, pull requests merged in 2019-10, with the labels that each got.

#597 More CBC tests
  scripts/test-fuzzed-plaintext.py
  tests/tlslite-ng-random-subset.json
  tests/tlslite-ng.json
Labels: new test script

#599 update expected sigalgs to new tlslite-ng version
  scripts/test-certificate-request.py
  scripts/test-certificate-verify-malformed.py
  scripts/test-rsa-pss-sigs-on-certificate-verify.py
  scripts/test-tls13-certificate-request.py
  scripts/test-tls13-certificate-verify.py
Labels: maintenance

#600 Remove leftover .gitmodules file.
  .gitmodules
Labels: maintenance

#601 more test coverage for CertificateVerifyGenerator
  tests/test_tlsfuzzer_messages.py
Labels: maintenance

#604 ECDSA support on client side
  .codeclimate.yml
  requirements.txt
  scripts/test-ecdsa-in-certificate-verify.py
  scripts/test-tls13-ecdsa-in-certificate-verify.py
  tests/test_tlsfuzzer_messages.py
  tests/tlslite-ng-random-subset.json
  tests/tlslite-ng.json
  tlsfuzzer/helpers.py
  tlsfuzzer/messages.py
Labels: enhancement
