Repository tlsfuzzer/tlsfuzzer, pull requests merged in 2019-02, with the labels that each got.

#508 freeze some python 3.3 requirements
  build-requirements-3.3.txt
Labels: maintenance

#507 Downgrade sentinel
  tests/test_tlsfuzzer_expect.py
  tlsfuzzer/expect.py
Labels: bug

#500 add documentation describing usage of test-record-size-limit.py
  USAGE.md
Labels: maintenance

#502 fix typo in test-rsa-pss-sigs-on-certificate-verify.py
  scripts/test-rsa-pss-sigs-on-certificate-verify.py
Labels: maintenance

#504 record-size-limit: Fix test name duplication
  scripts/test-record-size-limit.py
  tlsfuzzer/expect.py
Labels: bug

#506 More record size limit tests
  scripts/test-record-size-limit.py
  tlsfuzzer/expect.py
Labels: new test script

#510 moar badge(r)s!
  README.md
Labels: maintenance

#511 remove unused import
  tlsfuzzer/messages.py
Labels: maintenance

#509 Export cipher fixes
  scripts/test-downgrade-protection.py
  scripts/test-export-ciphers-rejected.py
  tests/test_tlsfuzzer_helpers.py
  tests/tlslite-ng-random-subset.json
  tests/tlslite-ng.json
  tlsfuzzer/helpers.py
Labels: maintenance

#516 sig-algs: add support for RSA-PSS certs on server side
  scripts/test-sig-algs.py
  tests/tlslite-ng-random-subset.json
  tests/tlslite-ng.json
Labels: bug

#536 fix build on py3.2 and py3.3
  build-requirements-3.2.txt
  build-requirements-3.3.txt
Labels: maintenance

#517 differentiate close from timeout for ExpectClose()
  scripts/test-cve-2016-6309.py
  tlsfuzzer/runner.py
Labels: bug

#518 Strict Client Hello checks
  scripts/test-conversation.py
  scripts/test-tls13-conversation.py
  scripts/test-truncating-of-client-hello.py
Labels: new test script
