Repository tlsfuzzer/tlsfuzzer, pull requests merged in 2020-06, with the labels that each got.

#655 document integrating tlsfuzzer in CI
  .github/styles/vocab.txt
  docs/source/ci-integration.rst
  docs/source/glossary.rst
  docs/source/index.rst
  docs/source/theory.rst
Labels: maintenance

#656 New RFC testing
  docs/source/glossary.rst
  docs/source/index.rst
  docs/source/testimonials.rst
  docs/source/testing-extensions.rst
  docs/source/writing-tests.rst
Labels: maintenance

#659 [WIP] Add ability to collect timing information
  .travis.yml
  TIMING.md
  build-requirements-analysis.txt
  requirements-timing.txt
  scripts/test-bleichenbacher-timing.py
  scripts/test-conversation.py
  scripts/test-lucky13.py
  tests/capture.pcap
  tests/test_tlsfuzzer_analysis.py
  tests/test_tlsfuzzer_extract.py
  tests/test_tlsfuzzer_messages.py
  tests/test_tlsfuzzer_timing_runner.py
  tests/test_tlsfuzzer_utils_log.py
  tests/tlslite-ng-random-subset.json
  tests/tlslite-ng.json
  tlsfuzzer/analysis.py
  tlsfuzzer/extract.py
  tlsfuzzer/messages.py
  tlsfuzzer/timing_runner.py
  tlsfuzzer/utils/log.py
  tlsfuzzer/utils/statics.py
Labels: enhancement

#674 Speed up tests
  scripts/test-aesccm.py
  scripts/test-certificate-malformed.py
  scripts/test-dhe-no-shared-secret-padding.py
  scripts/test-dhe-rsa-key-exchange-signatures.py
  scripts/test-ecdhe-padded-shared-secret.py
  scripts/test-heartbeat.py
  scripts/test-serverhello-random.py
  scripts/test-tls13-dhe-shared-secret-padding.py
  scripts/test-tls13-version-negotiation.py
  tests/tlslite-ng-random-subset.json
  tests/tlslite-ng.json
Labels: bug

#668 FFDH parameter matching
  requirements.txt
  scripts/test-ffdhe-expected-params.py
  tests/test_tlsfuzzer_expect.py
  tests/tlslite-ng-random-subset.json
  tests/tlslite-ng.json
  tlsfuzzer/expect.py
Labels: enhancement

#675 test-sig-algs: advertise supported groups
  scripts/test-sig-algs.py
Labels: new test script
