Repository tlsfuzzer/tlsfuzzer, pull requests merged in 2020-08, with the labels that each got.

#687 timing-analysis: make sure that code actually shows up on rtd.io
  docs/source/timing-analysis.rst
Labels: maintenance

#686 External time source
  .gitignore
  docs/source/timing-analysis.rst
  tests/test.log
  tests/test_tlsfuzzer_extract.py
  tests/times-log.csv
  tlsfuzzer/analysis.py
  tlsfuzzer/extract.py
Labels: enhancement

#690 Fix docs for rtd.io
  docs/source/timing-analysis.rst
Labels: maintenance

#691 dhe-rsa-key-exchange-with-bad-messages: fix version
  scripts/test-dhe-rsa-key-exchange-with-bad-messages.py
Labels: maintenance

#689 Faster and more detailed analysis
  .travis.yml
  build-requirements-2.6.txt
  build-requirements-3.3.txt
  build-requirements.txt
  docs/source/timing-analysis.rst
  tests/test_tlsfuzzer_analysis.py
  tests/test_tlsfuzzer_combine.py
  tests/test_tlsfuzzer_extract.py
  tlsfuzzer/analysis.py
  tlsfuzzer/combine.py
  tlsfuzzer/extract.py
Labels: enhancement

#678 fixup ordered_dict for Python 3.9
  .travis.yml
  Makefile
  tlsfuzzer/utils/ordered_dict.py
Labels: maintenance

#693 Lower mem usage
  tests/test_tlsfuzzer_analysis.py
  tlsfuzzer/analysis.py
Labels: enhancement

#694 Add a TLSv1.3 test that ensures a zero content type is handled correctly
  scripts/test-tls13-zero-content-type.py
  tests/tlslite-ng-random-subset.json
  tests/tlslite-ng.json
Labels: new test script
