Repository tlsfuzzer/tlsfuzzer, pull requests merged in 2021-03, with the labels that each got.

#743 Freeze tlslite-ng version, update for new python 3.7
  .github/workflows/ci.yml
  requirements.txt
Labels: maintenance

#740 FIPS compatibility for tests
  scripts/test-certificate-verify-malformed-sig.py
  scripts/test-rsa-sigs-on-certificate-verify.py
  tests/tlslite-ng-random-subset.json
  tests/tlslite-ng.json
Labels: bug, enhancement

#745 Fix pip on older pythons
  .github/workflows/ci.yml
Labels: maintenance

#744 sslv2-force-cipher: clarify where the test applies
  scripts/test-sslv2-force-cipher.py
Labels: maintenance

#747 disable vale
  .github/workflows/main.yml
Labels: maintenance

#733 add -d to negotiate (ec)dhe ciphers in test-tls13-version-negotiation.py
  scripts/test-tls13-version-negotiation.py
  tests/tlslite-ng-random-subset.json
  tests/tlslite-ng.json
Labels: enhancement

#748 add test case to check sig_algs with renegotiation and resumption
  scripts/test-sig-algs-renegotiation-resumption.py
  tests/tlslite-ng-random-subset.json
  tests/tlslite-ng.json
Labels: enhancement, new test script
